### ISSUE TITLE
Problem upgrading to Moodle 4.4

### ISSUE THREAD

**Issue by lassnj** [catalyst/moodle-tool_forcedcache#53]
We just upgraded our site to moodle 4.4.1+ and the latest commit in tool_forcedcache produced the following error: 

```
Fatal error: Uncaught Error: Class "Redis" not found in /data/web/www/vhosts/mysite.net/admin/tool/forcedcache/classes/cache_config.php:240
Stack trace:
#0 /data/web/www/vhosts/mysite.net/admin/tool/forcedcache/classes/cache_config.php(95): tool_forcedcache_cache_config->generate_store_instance_config(Array)
#1 /data/web/www/vhosts/mysite.net/admin/tool/forcedcache/classes/cache_config.php(64): tool_forcedcache_cache_config->generate_config_array()
#2 /data/web/www/vhosts/mysite.net/admin/tool/forcedcache/classes/cache_config.php(479): tool_forcedcache_cache_config->include_configuration()
#3 /data/web/www/vhosts/mysite.net/admin/tool/forcedcache/classes/cache_config_writer.php(77): tool_forcedcache_cache_config->include_configuration_wrapper()
#4 /data/web/www/vhosts/mysite.net/cache/classes/config.php(138): tool_forcedcache_cache_config_writer->include_configuration()
#5 /data/web/www/vhosts/mysite.net/admin/tool/forcedcache/classes/cache_factory.php(61): cache_config->load()
#6 /data/web/www/vhosts/mysite.net/cache/classes/helper.php(675): tool_forcedcache_cache_factory->create_config_instance(true)
#7 /data/web/www/vhosts/mysite.net/cache/classes/helper.php(705): cache_helper::update_site_identifier('xyz')
#8 /data/web/www/vhosts/mysite.net/cache/classes/definition.php(962): cache_helper::get_site_identifier()
#9 /data/web/www/vhosts/mysite.net/cache/classes/definition.php(887): cache_definition->get_cache_identifier()
#10 /data/web/www/vhosts/mysite.net/cache/classes/helper.php(642): cache_definition->generate_single_key_prefix()
#11 /data/web/www/vhosts/mysite.net/cache/classes/loaders.php(1229): cache_helper::hash_key('de_core_error_0', Object(cache_definition))
#12 /data/web/www/vhosts/mysite.net/cache/classes/loaders.php(517): cache->parse_key('de_core_error_0')
#13 /data/web/www/vhosts/mysite.net/cache/classes/loaders.php(418): cache->get_implementation('de_core_error_0', -1, 0)
#14 /data/web/www/vhosts/mysite.net/lib/classes/string_manager_standard.php(124): cache->get('de_core_error_0')
#15 /data/web/www/vhosts/mysite.net/lib/classes/string_manager_standard.php(280): core_string_manager_standard->load_component_strings('core_error', 'de')
#16 /data/web/www/vhosts/mysite.net/lib/setuplib.php(605): core_string_manager_standard->string_exists('generalexceptio...', 'error')
#17 /data/web/www/vhosts/mysite.net/lib/setuplib.php(439): get_exception_info(Object(Error))
#18 [internal function]: default_exception_handler(Object(Error))
#19 {main}
  thrown in /data/web/www/vhosts/mysite.net/admin/tool/forcedcache/classes/cache_config.php on line 240
```

Any idea, what could be the problem?

Thanks a lot!

**Comment by SashaAnastasi** [comment]
Hi @lassnj can you please confirm the latest commit you're referring to?

**Comment by davidpesce** [comment]
Did you compile php-redis for the version of PHP you're using?

**Comment by lassnj** [comment]
Hi, sorry for the late reply. Apparently one of your later commits fixed the issue. We cannot reproduce it anymore.
